import type { EquipmentClaimProvenanceGraph, EquipmentClaimIdentityAssertion, EquipmentNormalizedClaim, EquipmentSourceClaim } from "./equipment-claim-provenance.types.js";

const atlasUsa: EquipmentClaimIdentityAssertion = { id: "identity-atlas-usa-2026-30-20", certainty: "exact_variant_match", manufacturer: "Louisville Slugger", model: "Atlas", modelYear: 2026, certification: "USA", lengthInches: 30, weightOunces: 20, drop: -10, sku: "LS-ATLAS-USA-30-20", equipmentId: "atlas-usa", equipmentVariantId: "atlas-usa-30-20", limitations: [] };
const atlasBbcor: EquipmentClaimIdentityAssertion = { ...atlasUsa, id: "identity-atlas-bbcor-2026", certification: "BBCOR", sku: "LS-ATLAS-BBCOR-30-27", equipmentId: "atlas-bbcor", equipmentVariantId: "atlas-bbcor-30-27", weightOunces: 27, drop: -3 };
const atlas2025: EquipmentClaimIdentityAssertion = { ...atlasUsa, id: "identity-atlas-usa-2025", modelYear: 2025, equipmentId: "atlas-usa-2025", equipmentVariantId: "atlas-usa-2025-30-20" };
const ambiguousAtlas: EquipmentClaimIdentityAssertion = { id: "identity-atlas-ambiguous", certainty: "ambiguous", manufacturer: "Louisville Slugger", model: "Atlas", limitations: ["Model year, certification, and variant are unknown."] };

export function buildSyntheticEquipmentClaimProvenanceFixture(): EquipmentClaimProvenanceGraph {
  const rawClaims: EquipmentSourceClaim[] = [
    raw("claim-manufacturer-spec", "manufacturer", "doc-manufacturer", "factual_specification", "identity-atlas-usa-2026-30-20", "lineage-manufacturer", "authoritative"),
    ...["a", "b", "c"].map((suffix) => raw(`claim-retailer-${suffix}`, `retailer-${suffix}`, `doc-retailer-${suffix}`, "factual_specification", "identity-atlas-usa-2026-30-20", "lineage-manufacturer", "secondary")),
    raw("claim-reviewer", "reviewer", "doc-review", "subjective_observation", "identity-atlas-usa-2026-30-20", "lineage-reviewer", "observational", "easy to get through the zone"),
    raw("claim-marketing", "manufacturer", "doc-manufacturer", "marketing_claim", "identity-atlas-usa-2026-30-20", "lineage-manufacturer-marketing", "not_authoritative_for_claim", "massive sweet spot"),
    raw("claim-conflict", "measurement", "doc-measurement", "measurement_observation", "identity-atlas-usa-2026-30-20", "lineage-measurement", "primary", "barrel diameter 2.5 inches"),
    raw("claim-model", "model", "doc-model", "modeled_output", "identity-atlas-usa-2026-30-20", "lineage-manufacturer", "unknown", "estimated nominal weight 20 ounces"),
    { ...raw("claim-historical", "manufacturer", "doc-old", "factual_specification", "identity-atlas-usa-2025", "lineage-old", "authoritative"), verificationState: "superseded" },
    { ...raw("claim-current", "manufacturer", "doc-manufacturer", "factual_specification", "identity-atlas-usa-2026-30-20", "lineage-manufacturer", "authoritative"), supersedesClaimId: "claim-historical" }
  ];
  const normalizedClaims: EquipmentNormalizedClaim[] = [
    normalized("norm-length", "claim-manufacturer-spec", "nominal_length", 30, "inches"), normalized("norm-weight", "claim-manufacturer-spec", "nominal_weight", 20, "ounces"), normalized("norm-drop", "claim-manufacturer-spec", "drop", -10), normalized("norm-barrel-manufacturer", "claim-current", "barrel_diameter", 2.625, "inches"),
    ...["a", "b", "c"].map((suffix) => normalized(`norm-retailer-${suffix}`, `claim-retailer-${suffix}`, "barrel_diameter", 2.625, "inches")),
    { ...normalized("norm-review", "claim-reviewer", "qualitative_descriptor", "easy_to_swing"), normalizationMethod: "controlled_vocabulary" as const, evidenceClass: "structured_human_evaluation" as const, verificationState: "unverified_extracted" as const, reviewState: "review_pending" as const },
    { ...normalized("norm-marketing", "claim-marketing", "marketing_descriptor", "massive_sweet_spot"), evidenceClass: "verified_catalog_fact" as const },
    { ...normalized("norm-barrel-measured", "claim-conflict", "barrel_diameter", 2.5, "inches"), evidenceClass: "direct_physical_measurement" as const },
    { ...normalized("norm-model", "claim-model", "nominal_weight_estimate", 20, "ounces"), normalizationMethod: "model_output" as const, evidenceClass: "modeled_estimate" as const },
    normalized("norm-historical", "claim-historical", "barrel_diameter", 2.6, "inches", "superseded")
  ];
  return {
    version: "1.0",
    sources: [source("manufacturer", "Louisville Slugger", "manufacturer_primary"), source("retailer-a", "Retailer A", "retailer"), source("retailer-b", "Retailer B", "retailer"), source("retailer-c", "Retailer C", "retailer"), source("reviewer", "Independent Reviewer", "independent_expert_review"), source("measurement", "Synthetic Measurement Lab", "ninery_internal_measurement"), source("model", "Synthetic Model", "derived_model_output")],
    documents: [document("doc-manufacturer", "manufacturer", "manufacturer.example/atlas", "2026-01-01"), document("doc-retailer-a", "retailer-a", "retailer-a.example/atlas"), document("doc-retailer-b", "retailer-b", "retailer-b.example/atlas"), document("doc-retailer-c", "retailer-c", "retailer-c.example/atlas"), document("doc-review", "reviewer", "review.example/atlas"), document("doc-measurement", "measurement", "synthetic:measurement"), document("doc-model", "model", "synthetic:model"), { ...document("doc-old", "manufacturer", "manufacturer.example/atlas/2025", "2025-01-01"), availability: "historical" }],
    extractionRuns: [{ id: "extract-manual", method: "manual", extractorType: "human", extractorId: "fixture-author", extractorVersion: "1.0", executedAt: "2026-09-08T00:00:00.000Z", schemaVersion: "1.0", reviewState: "reviewed_accepted" }, { id: "extract-ai", method: "ai_assisted", extractorType: "ai_model", extractorId: "synthetic-extractor", extractorVersion: "1.2", executedAt: "2026-09-08T00:00:00.000Z", schemaVersion: "1.0", reviewState: "review_pending" }],
    identities: [atlasUsa, atlasBbcor, atlas2025, ambiguousAtlas], rawClaims, normalizedClaims,
    dependencies: [{ id: "dep-original", claimId: "claim-manufacturer-spec", dependencyType: "original", dependencyRationale: "Original manufacturer claim.", reviewedState: "reviewed_accepted" }, ...["a", "b", "c"].map((suffix) => ({ id: `dep-retailer-${suffix}`, claimId: `claim-retailer-${suffix}`, upstreamClaimId: "claim-manufacturer-spec", dependencyType: "syndicated_from" as const, dependencyRationale: "Synthetic retailer copy of manufacturer feed.", reviewedState: "reviewed_accepted" as const })), { id: "dep-review", claimId: "claim-reviewer", dependencyType: "independent_observation", dependencyRationale: "Synthetic independent observation.", reviewedState: "reviewed_accepted" }, { id: "dep-model", claimId: "claim-model", upstreamClaimId: "claim-manufacturer-spec", dependencyType: "derived_from", dependencyRationale: "Synthetic model derivative.", reviewedState: "reviewed_accepted" }],
    constructRelationships: [{ id: "relationship-review", normalizedClaimId: "norm-review", construct: "startup_demand", role: "candidate_only", mappingMethod: "controlled_vocabulary", mappingVersion: "1.0", reviewState: "review_pending", rationale: "Descriptor is a candidate relationship, not a construct conclusion.", limitations: ["Tester context is synthetic."], constructValueCreated: false }, { id: "relationship-marketing", normalizedClaimId: "norm-marketing", construct: "usable_contact_region_breadth", role: "not_applicable", mappingMethod: "keyword_candidate", mappingVersion: "1.0", reviewState: "reviewed_rejected", rationale: "Marketing language is not behavioral evidence.", limitations: [], constructValueCreated: false }],
    modeledLineages: [{ normalizedClaimId: "norm-model", modelId: "synthetic-model", modelVersion: "0.1", inputNormalizedClaimIds: ["norm-weight"], inputIndependenceGroupIds: ["lineage-manufacturer"], createdAt: "2026-09-08T00:00:00.000Z", limitations: ["Fixture only; not production evidence."] }]
  };
}

function source(id: string, displayName: string, sourceType: Parameters<typeof typedSource>[2]) { return typedSource(id, displayName, sourceType); }
function typedSource(id: string, displayName: string, sourceType: import("./equipment-claim-provenance.types.js").EquipmentSourceType) { return { id, displayName, sourceType, state: "active" as const, version: "1.0" }; }
function document(id: string, sourceId: string, sourceReference: string, publishedAt?: string) { return { id, sourceId, documentType: "product_page" as const, sourceReference, title: id, publishedAt, retrievedAt: "2026-09-08T00:00:00.000Z", modelYear: 2026, revision: "1", contentFingerprint: `fingerprint-${id}`, availability: "available" as const }; }
function raw(id: string, sourceId: string, documentId: string, claimType: import("./equipment-claim-provenance.types.js").EquipmentClaimType, identityAssertionId: string, independenceGroupId: string, authority: import("./equipment-claim-provenance.types.js").EquipmentClaimAuthority, rawText = "30-inch -10 model weighs 20 ounces"): EquipmentSourceClaim { return { id, sourceId, documentId, rawText, claimType, identityAssertionId, extractionRunId: id === "claim-reviewer" ? "extract-ai" : "extract-manual", verificationState: id === "claim-reviewer" ? "unverified_extracted" : "source_confirmed", reviewState: id === "claim-reviewer" ? "review_pending" : "reviewed_accepted", independenceGroupId, authority, authorityRationale: "Claim-specific synthetic fixture authority.", limitations: ["Synthetic fixture; not real evidence."] }; }
function normalized(id: string, rawClaimId: string, claimKey: string, normalizedValue: unknown, normalizedUnit?: string, verificationState: import("./equipment-claim-provenance.types.js").EquipmentClaimVerificationState = "source_confirmed"): EquipmentNormalizedClaim { return { id, rawClaimId, claimKey, normalizedValue, normalizedUnit, normalizationMethod: "identity", normalizationVersion: "1.0", evidenceClass: "verified_catalog_fact", verificationState, reviewState: "reviewed_accepted", identityAssertionId: rawClaimId === "claim-historical" ? "identity-atlas-usa-2025" : "identity-atlas-usa-2026-30-20", limitations: ["Synthetic fixture; not real evidence."] }; }
