import type { MultiSourceEvidenceClass } from "../equipment-multi-source-strategy.types.js";

export const equipmentSourceTypeValues = ["manufacturer_primary", "certification_authority", "official_product_documentation", "retailer", "independent_expert_review", "structured_testing_publication", "user_review", "community_discussion", "ninery_internal_measurement", "ninery_internal_evaluation", "ninery_controlled_test", "ninery_structured_field_observation", "derived_model_output"] as const;
export type EquipmentSourceType = (typeof equipmentSourceTypeValues)[number];
export const equipmentClaimTypeValues = ["factual_specification", "subjective_observation", "comparative_observation", "marketing_claim", "field_observation", "measurement_observation", "test_observation", "modeled_output", "certification_claim", "identity_claim"] as const;
export type EquipmentClaimType = (typeof equipmentClaimTypeValues)[number];
export const equipmentClaimVerificationStateValues = ["unverified_extracted", "source_confirmed", "corroborated", "conflicting", "review_required", "superseded"] as const;
export type EquipmentClaimVerificationState = (typeof equipmentClaimVerificationStateValues)[number];
export const equipmentClaimReviewStateValues = ["not_reviewed", "review_not_required", "review_pending", "reviewed_accepted", "reviewed_with_limitations", "reviewed_rejected"] as const;
export type EquipmentClaimReviewState = (typeof equipmentClaimReviewStateValues)[number];
export type EquipmentClaimDependencyType = "original" | "syndicated_from" | "derived_from" | "copied_from" | "shared_upstream" | "independent_observation" | "unknown_dependency";
export type EquipmentIdentityCertainty = "exact_variant_match" | "equipment_model_match" | "family_only" | "ambiguous" | "conflicting" | "unresolved";
export type EquipmentClaimAuthority = "authoritative" | "primary" | "secondary" | "observational" | "unknown" | "not_authoritative_for_claim";
export type EquipmentClaimConstructRole = "direct_construct_evidence" | "supporting_context" | "calibration_evidence" | "not_applicable" | "candidate_only";

export type EquipmentSource = { readonly id: string; readonly displayName: string; readonly sourceType: EquipmentSourceType; readonly publisherIdentity?: string; readonly operatorIdentity?: string; readonly state: "active" | "historical"; readonly version: string };
export type EquipmentSourceDocument = { readonly id: string; readonly sourceId: string; readonly documentType: "product_page" | "specification_sheet" | "retailer_page" | "review_article" | "review_video_transcript" | "certification_listing" | "measurement_packet" | "survey_response" | "model_output"; readonly sourceReference: string; readonly title: string; readonly publishedAt?: string; readonly retrievedAt: string; readonly modelYear?: number; readonly revision?: string; readonly contentFingerprint?: string; readonly upstreamDocumentId?: string; readonly supersedesDocumentId?: string; readonly availability: "available" | "unavailable" | "historical" | "unknown" };
export type EquipmentExtractionRun = { readonly id: string; readonly method: "manual" | "deterministic_parser" | "ai_assisted"; readonly extractorType: "human" | "software" | "ai_model"; readonly extractorId: string; readonly extractorVersion: string; readonly executedAt: string; readonly schemaVersion: string; readonly reviewState: EquipmentClaimReviewState };
export type EquipmentClaimIdentityAssertion = { readonly id: string; readonly certainty: EquipmentIdentityCertainty; readonly manufacturer?: string; readonly model?: string; readonly modelYear?: number; readonly certification?: string; readonly constructionRevision?: string; readonly lengthInches?: number; readonly weightOunces?: number; readonly drop?: number; readonly sku?: string; readonly manufacturerProductId?: string; readonly upc?: string; readonly equipmentId?: string; readonly equipmentVariantId?: string; readonly limitations: readonly string[] };
export type EquipmentSourceClaim = { readonly id: string; readonly sourceId: string; readonly documentId: string; readonly sourceLocation?: string; readonly rawText?: string; readonly rawStructuredValue?: unknown; readonly claimType: EquipmentClaimType; readonly identityAssertionId: string; readonly extractionRunId: string; readonly verificationState: EquipmentClaimVerificationState; readonly reviewState: EquipmentClaimReviewState; readonly independenceGroupId: string; readonly authority: EquipmentClaimAuthority; readonly authorityRationale: string; readonly limitations: readonly string[]; readonly supersedesClaimId?: string };
export type EquipmentNormalizedClaim = { readonly id: string; readonly rawClaimId: string; readonly claimKey: string; readonly normalizedValue: unknown; readonly normalizedUnit?: string; readonly originalValue?: unknown; readonly originalUnit?: string; readonly normalizationMethod: "identity" | "unit_conversion" | "controlled_vocabulary" | "manual_interpretation" | "model_output"; readonly normalizationVersion: string; readonly evidenceClass: MultiSourceEvidenceClass; readonly verificationState: EquipmentClaimVerificationState; readonly reviewState: EquipmentClaimReviewState; readonly identityAssertionId: string; readonly limitations: readonly string[] };
export type EquipmentClaimDependency = { readonly id: string; readonly claimId: string; readonly upstreamClaimId?: string; readonly dependencyType: EquipmentClaimDependencyType; readonly dependencyRationale: string; readonly reviewedState: EquipmentClaimReviewState };
export type EquipmentClaimConstructRelationship = { readonly id: string; readonly normalizedClaimId: string; readonly construct: string; readonly role: EquipmentClaimConstructRole; readonly mappingMethod: "manual_review" | "controlled_vocabulary" | "policy_mapping" | "keyword_candidate"; readonly mappingVersion: string; readonly reviewState: EquipmentClaimReviewState; readonly rationale: string; readonly limitations: readonly string[]; readonly constructValueCreated: false };
export type EquipmentModeledEstimateLineage = { readonly normalizedClaimId: string; readonly modelId: string; readonly modelVersion: string; readonly inputNormalizedClaimIds: readonly string[]; readonly inputIndependenceGroupIds: readonly string[]; readonly createdAt: string; readonly limitations: readonly string[] };

export type EquipmentClaimProvenanceGraph = { readonly version: "1.0"; readonly sources: readonly EquipmentSource[]; readonly documents: readonly EquipmentSourceDocument[]; readonly extractionRuns: readonly EquipmentExtractionRun[]; readonly identities: readonly EquipmentClaimIdentityAssertion[]; readonly rawClaims: readonly EquipmentSourceClaim[]; readonly normalizedClaims: readonly EquipmentNormalizedClaim[]; readonly dependencies: readonly EquipmentClaimDependency[]; readonly constructRelationships: readonly EquipmentClaimConstructRelationship[]; readonly modeledLineages: readonly EquipmentModeledEstimateLineage[] };
export type EquipmentClaimConflict = { readonly claimKey: string; readonly normalizedClaimIds: readonly string[]; readonly independenceGroupIds: readonly string[]; readonly state: "independent_disagreement"; readonly automaticWinnerSelected: false; readonly toleranceApplied: false };
export type EquipmentClaimProvenanceAnalysis = { readonly version: "1.0"; readonly documentCount: number; readonly rawClaimCount: number; readonly normalizedClaimCount: number; readonly sourceCount: number; readonly independentClaimGroupCount: number; readonly lineageGroups: readonly { readonly id: string; readonly rawClaimIds: readonly string[]; readonly normalizedClaimIds: readonly string[] }[]; readonly conflicts: readonly EquipmentClaimConflict[]; readonly firewalls: { readonly aiCreatedEvidenceSource: false; readonly normalizationIncreasedIndependence: false; readonly marketingCreatedBehavioralDNA: false; readonly constructValuesCreated: false; readonly modeledDerivativeCorroboratedInput: false; readonly writesPerformed: false; readonly recommendationImpact: "none" } };

export class EquipmentClaimProvenanceValidationError extends Error { constructor(readonly issues: readonly string[]) { super(`Invalid Equipment claim provenance graph: ${issues.join(", ")}`); } }
