export type HardFilterCode =
  | "CERTIFICATION_MISMATCH"
  | "CATEGORY_MISMATCH"
  | "EQUIPMENT_NOT_ACTIVE"
  | "DNA_PROFILE_NOT_PUBLIC"
  | "VARIANT_NOT_AVAILABLE"
  | "PROFILE_COMPLETENESS_TOO_LOW"
  | "EVIDENCE_CONFIDENCE_TOO_LOW"
  | "INSUFFICIENT_REQUIRED_CHARACTERISTICS";
